version: "3"
services:
  product:
    image: pagonxt/product
    build: product
    volumes:
      - ./product:/app
    ports:
      - 3001:3001

  account:
    image: pagonxt/account
    build: account
    volumes:
      - ./account:/app
    ports:
      - 3000:3000

  mongodb_accounts:
    image: mongo
    container_name: mongodb_accounts
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=123456789
      - MONGO_INITDB_DATABASE=accounts
    ports:
      - 27017:27017

  mysqldb_products:
    image: mysql
    container_name: mysqldb_products
    restart: always
    environment:
      MYSQL_DATABASE: product
      MYSQL_ROOT_USER: root
      MYSQL_USER: mysqluser
      MYSQL_ROOT_PASSWORD: mysqlpass
      MYSQL_PASSWORD: mysqlpass
    ports:
      - 3316:3316