version: "3"
services:
  product:
    image: pagonxt/product
    build: product
    volumes:
      - ./product:/app
    ports:
      - 3001:3001

  account:
    image: pagonxt/account
    build: account
    volumes:
      - ./account:/app
    ports:
      - 3000:3000

  mongodb_accounts:
    image: mongo
    container_name: mongodb_accounts
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=123456789
      - MONGO_INITDB_DATABASE=accounts
    ports:
      - 27017:27017

  postgresql_products:
    image: postgres
    container_name: postgresql_products
    restart: always
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=products
    ports:
      - 5432:5432