version: "3"
services:
  product:
    depends_on:
      - mysqldb_products
    image: pagonxt/product
    build: product
    entrypoint: 'npm run start:dev'
    volumes:
      - ./product:/app
    ports:
      - 3001:3001

  account:
    depends_on:
      - mongodb_accounts
    image: pagonxt/account
    build: account
    entrypoint: 'npm run start:dev'
    volumes:
      - ./account:/app
    ports:
      - 3000:3000

  mongodb_accounts:
    image: mongo
    restart: always
    env_file: mongo.env

    ports:
      - 27017:27017
  
  mysqldb_products:
    image: mysql
    restart: always
    env_file: mysql.env
    ports:
      - 3306:3306