version: "3"
services:
  product:
    depends_on:
      - mysqldb_products
    image: pagonxt/product
    build: product
    volumes:
      - ./product:/app
    ports:
      - 3001:3001

  account:
    depends_on:
      - mongodb_accounts
    image: pagonxt/account
    build: account
    volumes:
      - ./account:/app
    ports:
      - 3000:3000

  mongodb_accounts:
    image: mongo
    container_name: mongodb_accounts
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=123456789
      - MONGO_INITDB_DATABASE=accounts
    ports:
      - 27017:27017
  
  mysqldb_products:
    image: mysql
    restart: always
    environment: 
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpass
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=products
    ports:
      - 3306:3306