version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=123456789
      - MONGO_INITDB_DATABASE=accounts
    ports:
      - 27017:2701

  product:
    image: pagonxt/product
    build: product

  account:
    image: pagonxt/account
    build: account
