openapi: 3.0.1
info:
  version: 2.0.0
  title: Accounts API
  description: Restful API that deals with Accounts
  contact:
    name: Bruna
    email: bruna.rastelli@gmail.com
servers:
  - url: 'http://localhost:3000'
    description: Server 1
paths:
  /account:
    summary: creates an account
    description: 'Given provided account data, creates an account'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        201:
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        400:
          description: Account not created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /tokens:
    summary: creates an account token
    description: 'Given email and password, creates an account token'
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
                password:
                  type: string
      responses:
        201:
          description: Token account created
          content:
            application/json:
              schema:
                type: object
                properties: 
                  token:
                    type: string
        401:
          description: Error with account data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:  
                    type: string

components:
  schemas:
    CreateAccountRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    AccountResponse:
      type: object
      properties:
        id: 
          type: string
        name:
          type: string
        email:
          type: string
        createdDate:
          type: string